source ~/bin/win-sudo/s/path.sh
alias g='git'
alias ga='git add'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gb='git branch'
alias gco='git checkout'
alias gc='git commit'
alias i='ionic'
alias is='ionic serve'
alias ls='ls -a'
alias n='npm'
